Ukol/Ukol/ViewModels/Data.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ukol.ViewModels
{
    public class Data
    {
        public int FromEntry { get; set; }
        public int ToEntry { get; set; }
        public int Range => ToEntry - FromEntry;

        //generování random čísla

    }
}

Ukol/Ukol/ViewModels/Logik.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ukol.ViewModels
{
    public class Logik
    {
        public int FromEntry { get; set; }
        public int ToEntry { get; set; }
        public int Secret { get; set; }
        public int Guess { get; set; }
        public bool Win { get; set; } = false;
        public bool Restart { get; set; } = true;
    }
}

Ukol/Ukol/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ukol.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Ukol/Ukol/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Ukol.ViewModels;

namespace Ukol.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public Logik Data{get;set;}

        public void OnGet()
        {
            Data = new Logik { FromEntry = 0,ToEntry=0 };
        }
        public void OnGetRange(int from, int to)
        {
            Data = new Logik { FromEntry = from, ToEntry = to};
            Data.Secret = makeSecret(to);
        }

        public int makeSecret(int to)
        {
            Random rnd = new Random();
            int rndvalue = rnd.Next(1,to);
            return rndvalue;
        }
    }
}

Ukol/Ukol/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ukol.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Ukol/Ukol/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Logik page";
}
@if (Model.Data.Restart)
{
    <h1>Logik</h1>

    <div>
        <ul>
            <li><a asp-page="./index" asp-page-handler="Range" asp-route-from="1" asp-route-to="10">1 to 10</a></li>
            <li><a asp-page="./index" asp-page-handler="Range" asp-route-from="1" asp-route-to="100">1 to 100</a></li>
            <li><a asp-page="./index" asp-page-handler="Range" asp-route-from="1" asp-route-to="1000">1 to 1000</a></li>
        </ul>
    </div>
}

@{if (Model.Data.ToEntry != 0)
    {
        <form>
            <p>Myslím si číslo..</p>
            <input />
            <button>Hádám</button>
        </form>
    }
}
@{if (Model.Data.Win)
    {
        <div>
            <p>Výhra!</p>
            <button>HRÁT ZNOVU</button>
        </div>
    }
}

Ukol/Ukol/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>